version: "3.8"

services:
  palarm-web:
    container_name: palarm-web
    build:
      context: web/
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - GENERATE_SOURCEMAP=false
    networks:
      - proxy
    labels:
      - 'autoheal=true'
      - 'traefik.enable=true'
      - 'traefik.http.routers.palarm-web.rule=Host(`palarm.myngz.com`)'
      - 'traefik.http.routers.palarm-web.entrypoints=websecure'
      - 'traefik.http.routers.palarm-web.tls.certresolver=letsencrypt'
  palarm-server:
    container_name: palarm-server
    build:
      context: server/
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy
    labels:
      - 'autoheal=true'
      - 'traefik.enable=true'
      - 'traefik.http.routers.palarm-server.rule=Host(`palarm.myngz.com`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.palarm-server.entrypoints=websecure'
      - 'traefik.http.routers.palarm-server.tls.certresolver=letsencrypt'
      - 'traefik.http.services.palarm-server.loadbalancer.server.port=5000'

networks:
  proxy:
    external: false
    name: proxy
