version: "3.8"

services:
  web:
    hostname: palarm-web
    ports:
      - 80
    build:
      context: web/
      dockerfile: Dockerfile
    restart: always
    environment:
      - GENERATE_SOURCEMAP=false
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.palarm-web.rule=Host(`palarm.myngz.com`)'
      - 'traefik.http.routers.palarm-web.entrypoints=websecure'
      - 'traefik.http.routers.palarm-web.tls.certresolver=letsencrypt'
  server:
    hostname: palarm-server
    ports:
      - 5000
    build:
      context: server/
      dockerfile: Dockerfile
    restart: always
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.palarm-server.rule=Host(`palarm.myngz.com`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.palarm-server.entrypoints=websecure'
      - 'traefik.http.routers.palarm-server.tls.certresolver=letsencrypt'
      - 'traefik.http.services.palarm-server.loadbalancer.server.port=5000'

networks:
  proxy:
    external: false
    name: proxy
