version: "3.4"

services:
  web:
    hostname: palarm-web
    # ports:
    #   - 666:666
    build:
      context: web/
      dockerfile: Dockerfile
    restart: always
    environment:
      - GENERATE_SOURCEMAP=false
      - SERVER_HOST=http://palarm-server:5000
      - NGINX_PORT=666
    networks:
      - nginx-pm_default
  server:
    hostname: palarm-server
    # ports:
    #   - 5000:5000
    build:
      context: server/
      dockerfile: Dockerfile
    restart: always
    networks:
      - nginx-pm_default


networks:
  nginx-pm_default:
    external: false
    name: nginx-pm_default
