export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_ATTRIBUTE = "DELETE_ATTRIBUTE";
export const ADD_ATTRIBUTE = "ADD_ATTRIBUTE";
export const EMPTY_PRODUCT_STATE = "EMPTY_PRODUCT_STATE";

export const CREATE_PRICE_ALERT = "CREATE_PRICE_ALERT";
export const GET_PRICE_ALERTS = "GET_PRICE_ALERTS"
export const DELETE_PRICE_ALERT = "DELETE_PRICE_ALERT"
export const EDIT_PRICE_ALERT = "EDIT_PRICE_ALERT"
export const UPDATE_PRICE_ALERT = "UPDATE_PRICE_ALERT"
export const CREATE_ALERT_FROM_LINK = "CREATE_ALERT_FROM_LINK"

export const SEARCH = "SEARCH"
export const SEARCH_UPDATE = "SEARCH_UPDATE"